### PR TITLE
#292  Check if Keychain was locked and try to unlock it

### LINKED ISSUE #292: Build must fail immediately when codesigning fails
When the codesign command fails with 'errSecInternalComponent', the build doesn't fail immediately:
`PB Command for codesign: codesign --force --sign ...... --entitlements ...Maven/HelloFX/target/client/arm64-ios/gvm/tmp/Entitlements.plist --verbose .../Maven/HelloFX/target/client/arm64-ios/hellofx.app`
`samples/Maven/HelloFX/target/client/arm64-ios/hellofx.app: errSecInternalComponent`
`Result for codesign: true`

The return value of the process is 1, but the build continues here and fails later on which is confusing. 

Instead it should immediately stop. 
Furthermore, the build could add a hint on what to do. In this case, I was running on a remote machine using ssh, so I didn't get a prompt to unlock the keychain, so I had to it unlock it using:

`security -v unlock-keychain -p ... /Users/..../Library/Keychains/login.keychain-db`

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #292

### CODE REVIEW

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/util/ios/CodeSigning.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=4985392&bid=16461828)

File: src/main/java/com/gluonhq/substrate/util/ios/CodeSigning.java [hunk 1]
```diff
@@ -243,6 +246,15 @@ private boolean sign(Path entitlementsPath, Path appPath) throws IOException, In
             Logger.logSevere("Codesign process failed");
             return false;
         }
+        for (String line : runner.getResponses()) {
+            if (line.contains(KEYCHAIN_ERROR_MESSAGE)) {
+                Logger.logInfo("Error signing the application: keychain was locked");
```
Comment (johanvos) [inline src/main/java/com/gluonhq/substrate/util/ios/CodeSigning.java]: That sounds like the operation is halted, but from the code it seems you're continuing trying to solve this.
It would be good if the developer got feedback (e.g. "You will know be shown a dialog" or so)

Comment (jperedadnr) [reply src/main/java/com/gluonhq/substrate/util/ios/CodeSigning.java]: Makes sense, modified.

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/util/ios/CodeSigning.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=4985392&bid=16461828)
