### PR TITLE
Use JAVA_HOME/bin/jar

### LINKED ISSUE #689: Cannot run program "jar"
Follow up of https://github.com/gluonhq/client-samples/issues/91

If `JAVA_HOME/bin` is not in the user's `PATH`, running `jar ...` might fail. 

A proper fix that doesn't require the user modifying the PATH variable can be done by using `JAVA_HOME/bin/jar` or `GRAALVM_HOME/bin/jar`.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #689

### CODE REVIEW

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/model/ClassPath.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5813291&bid=19030807)

File: src/main/java/com/gluonhq/substrate/model/ClassPath.java [hunk 1]
```diff
@@ -120,10 +130,26 @@ public String mapWithLibs(Path libsPath, String... libNames) {
...
+                String javaPath = System.getenv("JAVA_HOME");
+                if (javaPath == null || javaPath.isEmpty()) {
+                    javaPath = System.getenv("GRAALVM_HOME");
+                    if (javaPath == null || javaPath.isEmpty()) {
+                        throw new IOException("Error: $JAVA_HOME and $GRAALVM_HOME are undefined");
+                    }
+                }
+                Path jarPath = Path.of(javaPath, "bin", "jar");
+                if (!Files.exists(jarPath)) {
+                    throw new IOException("Error: " + javaPath + " doesn't exist");
```
Comment (tiainen) [inline src/main/java/com/gluonhq/substrate/model/ClassPath.java:143]: Should be `jarPath` in the exception message.

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/model/ClassPath.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5813291&bid=19030807)
