### PR TITLE
#577 Use correct formatting in resourceList, avoiding duplicated jars

### LINKED ISSUE #577: Error parsing resource configuration file
The resource configuration file seems to be generated incorrectly when running the client plugin version 4.0.7 on Ubuntu to generate an Android package. The file looks like this:

```{
  "resources": [
    {"pattern": ".*\\.png$"},
    {"pattern": ".*\\.jpg$"},
    {"pattern": ".*\\.jpeg$"},
    {"pattern": ".*\\.gif$"},
    {"pattern": ".*\\.bmp$"},
    {"pattern": ".*\\.ttf$"},
    {"pattern": ".*\\.raw$"},
    {"pattern": ".*\\.xml$"},
    {"pattern": ".*\\.fxml$"},
    {"pattern": ".*\\.css$"},
    {"pattern": ".*\\.gls$"},
    {"pattern": ".*\\.json$"},
    {"pattern": ".*\\.license$"},
    {"pattern": ".*\\.frag$"},
    {"pattern": ".*\\.vert$"},
      {"pattern": ".*\\.nor$" }
      {"pattern": ".*\\.nor$" }
  ]
}
```

One can see that the last pattern shows up twice with a missing comma separator. The build throws this exception:

```
Error: Error parsing resource configuration in /home/parallels/IdeaProjects/evxcen-mobile/evxcen-app/target/client/aarch64-android/gvm/resourceconfig-aarch64-android.json:
[Tue May 05 03:09:11 PDT 2020][INFO] [SUB] line 19 column 6 Expected , or ] but found {
[Tue May 05 03:09:11 PDT 2020][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option ResourceConfigurationFiles.
```

I am using GraalVM ea28 for linux.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #577

### CODE REVIEW

File: src/test/java/com/gluonhq/substrate/model/ClassPathTests.java [hunk 1]
```diff
@@ -2,9 +2,12 @@
 
 import org.junit.jupiter.api.Test;
 
+import java.io.File;
```
Comment (eugener) [inline src/test/java/com/gluonhq/substrate/model/ClassPathTests.java:5]: Codacy Issue found: [Unused import - java.io.File.](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5473013)

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           

Complexity increasing per file
==============================
- src/test/java/com/gluonhq/substrate/config/ConfigTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5473013&bid=17937410)

File: src/test/java/com/gluonhq/substrate/model/ClassPathTests.java [hunk 2]
```diff
@@ -2,9 +2,12 @@
...
+import java.io.IOException;
 import java.nio.file.Path;
 import java.util.Arrays;
 import java.util.Collections;
+import java.util.List;
```
Comment (eugener) [inline src/test/java/com/gluonhq/substrate/model/ClassPathTests.java:10]: Codacy Issue found: [Unused import - java.util.List.](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5473013)

Comment (eugener) [inline src/test/java/com/gluonhq/substrate/model/ClassPathTests.java:10]: Codacy Issue found: [Avoid unused imports such as 'java.util.List'](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5473013)

File: src/test/java/com/gluonhq/substrate/model/ClassPathTests.java (hunk 1 above)
Comment (eugener) [inline src/test/java/com/gluonhq/substrate/model/ClassPathTests.java:5]: Codacy Issue found: [Avoid unused imports such as 'java.io.File'](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5473013)

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/test/java/com/gluonhq/substrate/config/ConfigTests.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5473013&bid=17937410)
