### PR TITLE
handle OpenJDK aligned GraalVM versions

### LINKED ISSUE #1221: Cannot use GraalVM for JDK 17 (23.0.0)
The internal version check in `InternalProjectConfiguration.checkGraalVMVersion` does not allow the new versioning scheme of GraalVM which breaks compilation with 23.0.0, which now reports 17.0.7 as version.

### Expected Behavior
I can use GraalVM for JDK 17 / 20

### Current Behavior
```java
java.io.IOException: Current GraalVM version (17.0.7) not supported.
Please upgrade to 22.1 or higher
	at com.gluonhq.substrate.model.InternalProjectConfiguration.checkGraalVMVersion(InternalProjectConfiguration.java:480)
	at com.gluonhq.substrate.SubstrateDispatcher.<init>(SubstrateDispatcher.java:381)
	at com.gluonhq.NativeBaseMojo.createSubstrateDispatcher(NativeBaseMojo.java:173)
	at com.gluonhq.NativeCompileMojo.execute(NativeCompileMojo.java:53)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

```

### Steps to Reproduce
compile anything with GraalVM for JDK 17 / 20

### Your Environment
GraalVM for JDK 17

### PR DESCRIPTION
**Pull request by kristofdho**
The GraalVM version check does not allow the latest GraalVM for JDK 17 / 20 to be used as it reports the JDK version instead of the old GraalVM version numbering.

### Issue

Fixes #1221

### Progress

- [ ] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: src/main/java/com/gluonhq/substrate/model/InternalProjectConfiguration.java [hunk 1]
```diff
@@ -474,25 +474,38 @@ public boolean usesJDK11() {
...
-            throw new IOException("Current GraalVM version (" + graalVersion + ") not supported.\n" +
-                    "Please upgrade to " + Constants.GRAALVM_MIN_VERSION + " or higher");
+    public void checkGraalVMVersion(Version javaVersion) throws IOException {
+        if (isOldGraalVMVersioningScheme(javaVersion)) {
+            Version graalVersion = getGraalVersion();
+            if (graalVersion.compareTo(new Version(Constants.GRAALVM_MIN_VERSION)) < 0) {
+                throw new IOException("Current GraalVM version (" + graalVersion + ") not supported.\n" +
+                        "Please upgrade to " + Constants.GRAALVM_MIN_VERSION + " or higher");
+            }
+        }
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/substrate/model/InternalProjectConfiguration.java:484]: This means that if there is a GraalVM build that uses the new GraalVM versioning system, there is no check at all if this build is older than the GraalVM_MIN_VERSION.
Of course, currently the min version is "22.1" (old system), so _any_ build with the new versioning system is newer, and whenever we increase that min value in the future, we should use the new versioning system and do a proper check at that point. 
For now, maybe adding something like: 
```
} else {
    // TODO: check the GraalVM version whenever Constants.GRAALVM_MIN_VERSION is bumped and uses the new versioning system
}
```
will do?

File: src/test/java/com/gluonhq/substrate/model/InternalProjectConfigurationTest.java [hunk 2]
```diff
@@ -0,0 +1,47 @@
+package com.gluonhq.substrate.model;
```
Comment (jperedadnr) [inline src/test/java/com/gluonhq/substrate/model/InternalProjectConfigurationTest.java:1]: Add license header

**Review by jperedadnr — COMMENTED** [review]
Looks good, tested and fixes the issue with recent GraalVM builds, while works on old builds.
Added some comments.

**Review by jperedadnr — APPROVED** [review]

**Review by johanvos — APPROVED** [review]
Nice work, thanks!
