### PR TITLE
Fail fast if JavaFX static path is set

### LINKED ISSUE #922: fail-fast in case there are no javafx jars on the classpath
In case for some reasons the JavaFX jars are not found on the classpath, but they are expected, we should not pass control to native-image but bail immediately.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fail fast if JavaFX static path is set but it is not valid, and also, when set, allow mapping and check files exist. 
A few more tests are included.

### Issue

Fixes #922

### Progress

- [ ] Change must not contain extraneous whitespace
- [ ] License header year is updated, if required
- [ ] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

**Review by eugener — APPROVED** [review]

File: src/main/java/com/gluonhq/substrate/model/InternalProjectConfiguration.java [hunk 1]
```diff
@@ -87,7 +87,20 @@ public InternalProjectConfiguration(ProjectConfiguration config) {
...
+                throw new IllegalArgumentException("Error: " + lib + " is not a valid SDK path.\n" +
+                        "Make sure you provide a valid JAVAFX_STATIC_SDK_PATH or unset it");
+            }
+            if (!Files.exists(lib.resolve("javafx.base.jar")) ||
+                    !Files.exists(lib.resolve("javafx.graphics.jar"))) {
+                throw new IllegalArgumentException("Error: " + lib + " doesn't contain required JavaFX jars.\n" +
+                        "Make sure you provide a valid JAVAFX_STATIC_SDK_PATH or unset it");
+            }
+        }
+        setJavaFXStaticSDK(javafxStaticSdkPath);  // this can be safely set even if null. Default will be used in that case
```
Comment (johanvos) [inline src/main/java/com/gluonhq/substrate/model/InternalProjectConfiguration.java:103]: Does this avoid a checksum check?

Comment (jperedadnr) [reply src/main/java/com/gluonhq/substrate/model/InternalProjectConfiguration.java:103]: The checksum check is only done when downloading from `FileDeps::resolvePath`:

```
        if (Files.exists(Objects.requireNonNull(path))) {
              return path;                                                // -> existing path
        }
        if (!setupDependencies()) {                           // -> download and check
        ...
        }
        
```

**Review by johanvos — APPROVED** [review]
