### PR TITLE
#606 Check correct cross compilation setup

### LINKED ISSUE #606: Prevent target Android from hosts other than Linux
Targeting Android from Windows or Mac should fail. CanCompile should be updated.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #606 

Fails fast checking if cross compilation can be done (before initializing the target, as that might lead to further attempts to install required software for such target).

### CODE REVIEW

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5557596&bid=18227814)

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5557596&bid=18227814)

File: src/main/java/com/gluonhq/substrate/model/Triplet.java [hunk 1]
```diff
@@ -114,9 +114,9 @@ public boolean canCompileTo(Triplet target) {
         // if the host os and target os are the same, always return true
         if (getOs().equals(target.getOs())) return true;
 
-        // if host is linux and target is ios, fail
-        return (!Constants.OS_LINUX.equals(getOs()) && !Constants.OS_WINDOWS.equals(getOs())) ||
-                !Constants.OS_IOS.equals(target.getOs());
+        // so far, iOS can be built from Mac, Android can be built from Linux
+        return (OS_DARWIN.equals(getOs()) && Constants.OS_IOS.equals(target.getOs())) ||
```
Comment (johanvos) [inline src/main/java/com/gluonhq/substrate/model/Triplet.java:118]: this will fail on Darwin as host and target

Comment (jperedadnr) [reply src/main/java/com/gluonhq/substrate/model/Triplet.java:118]: if returns true before when host and target are the same.

Comment (abhinayagarwal) [inline src/main/java/com/gluonhq/substrate/model/Triplet.java:118]: s/Constants.OS_IOS/OS_IOS

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=5557596&bid=18227814)

File: src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java [hunk 2]
```diff
@@ -310,6 +310,9 @@ public SubstrateDispatcher(Path buildRoot, ProjectConfiguration config) throws I
     }
 
     private TargetConfiguration getTargetConfiguration(Triplet targetTriplet) throws IOException {
+        if (!config.getHostTriplet().canCompileTo(targetTriplet)) {
```
Comment (johanvos) [inline src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java:313]: I don't think this check belongs here. We want to get the targetConfiguration, even if we can't compile to it.
(e.g. because we want to build in the cloud, or do other operations, e.g. link/run or so, that do not depend on compilation)

Comment (jperedadnr) [reply src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java:313]: Ok, but problem so far is that AndroidTarget will start downloading SDK once the target is set.

Comment (johanvos) [reply src/main/java/com/gluonhq/substrate/SubstrateDispatcher.java:313]: That is wrong, but has nothing to do with cross-compiling.
e.g. farm build allows for AndroidTarget on mac, but SDK should not be downloaded.

**Review by johanvos — APPROVED** [review]
We will have to revisit this when we allow cloud-builds, in which case the host triplet doesn't matter for this.
