### PR TITLE
Use latest Android build-tools

### LINKED ISSUE #255: AndroidTargetConfiguration has hard-coded values for Build Tools
AndroidTargetConfiguration uses hard-coded version i.e. `27.0.3` for build-tools. This forces Substrate to work only if the said version of the build-tools is installed. This is highly inflexible. Substrate should be able to use any version of build-tools present. 

To minimize unexpected behaviour, using the latest among all present build-tools versions is recommended.

### PR DESCRIPTION
**Pull request by abhinayagarwal**
Removes hard-coded version of build-tools and uses the latest version present in Android SDK path.

Fixes #255

### CODE REVIEW

File: src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java [hunk 1]
```diff
@@ -360,4 +362,20 @@ private void createDevelopKeystore() throws IOException, InterruptedException {
 
         System.err.println("done creating ks");
     }
+    
+    private String findLatestBuildTool(Path sdkPath) throws IOException {
+        Path buildToolsPath = sdkPath.resolve("build-tools");
+        if (buildToolsPath.toFile().exists()) {
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java]: Use `Files.exists(buildToolsPath)` instead

File: src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java [hunk 2]
```diff
@@ -360,4 +362,20 @@ private void createDevelopKeystore() throws IOException, InterruptedException {
 
         System.err.println("done creating ks");
     }
+    
+    private String findLatestBuildTool(Path sdkPath) throws IOException {
+        Path buildToolsPath = sdkPath.resolve("build-tools");
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java]: `Objects.requireNonNull(sdkPath)` and `Files.exists(sdkPath)`?

File: src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java [hunk 3]
```diff
@@ -360,4 +362,20 @@ private void createDevelopKeystore() throws IOException, InterruptedException {
...
+        if (buildToolsPath.toFile().exists()) {
+            Optional<Version> latest = Files.walk(buildToolsPath, 1)
+                    .filter(file -> Files.isDirectory(file) && !file.equals(buildToolsPath))
+                    .map(file -> new Version(file.getFileName().toString()))
+                    .max(Version::compareTo);
+            if (latest.isPresent()) {
```
Comment (jperedadnr) [inline src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java]: maybe you simplify it to something like `return Files.walk().filter().map().max(...).map(toString).orElseThrow(IOException)`?

File: src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java (hunk 2 above)
Comment (abhinayagarwal) [reply src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java]: Adding a check for `Files.exists(buildToolsPath)` makes `Files.exists(sdkPath)` redundant.
