### PR TITLE
Force the linker to call sunec

### LINKED ISSUE #733: URLConnection fails with JavaStaticSdk 11-ea+0
Follow up of https://github.com/gluonhq/client-maven-plugin/issues/216

After switching to JavaStatic 11-ea+0, (Http)URLConnection fails on Android and iOS.
```
[SUB] D/GraalCompiled(11552): Caused by: java.lang.UnsatisfiedLinkError: sun.security.ec.ECKeyPairGenerator.isCurveSupported([B)Z [symbol: Java_sun_security_ec_ECKeyPairGenerator_isCurveSupported or Java_sun_security_ec_ECKeyPairGenerator_isCurveSupported___3B]
[SUB] D/GraalCompiled(11552):   at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:153)
[SUB] D/GraalCompiled(11552):   at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
[SUB] D/GraalCompiled(11552):   at sun.security.ec.ECKeyPairGenerator.isCurveSupported(ECKeyPairGenerator.java)
```

The library `~/.gluon/substrate/javaStaticSdk/11-ea+0/ios-arm64/labs-staticjdk/lib/static/libsunec.a` contains `_JNI_OnLoad_sunec` and `_Java_sun_security_ec_ECKeyPairGenerator_isCurveSupported` symbols, however, these are not included with the current link command.

As a quick fix on iOS, moving `-lsunec` to `-Wl,-force_load,~/.gluon/substrate/javaStaticSdk/11-ea+0/ios-arm64/labs-staticjdk/lib/static/libsunec.a` solves the issue, as force_load includes all the symbols of the library.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #733

### CODE REVIEW

File: src/main/resources/native/android/c/launcher.c [hunk 1]
```diff
@@ -46,6 +46,7 @@ char *appDataDir;
 char *timeZone;
 
 int start_logger(const char *app_name);
+int JNI_OnLoad_sunec(JavaVM *vm, void *reserved);
```
Comment (johanvos) [inline src/main/resources/native/android/c/launcher.c:49]: Add a comment that links to the issue in GraalVM, so that we can safely revert this commit once it is fixed in a release that we support?

Comment (jperedadnr) [reply src/main/resources/native/android/c/launcher.c:51]: Done
