### PR TITLE
Link with clang++ and libstdc++ on Android

### LINKED ISSUE #840: Problem running on Pixel 5 / Android 11
I have created an APK with the client-maven-plugin and the app runs perfectly on my old Android 8 device.
However on my new Pixel 5 with Android 11 it doesn't even start.

Here is the relevant block from the USB logging that shows an UnsatisfiedLinError for libsubstrate.so:
```
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: QUALCOMM build                   : 35605c3, Ia11ce2d146
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Build Date                       : 09/02/20
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.31.04.00
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Local Branch                     : gfx-adreno.lnx.2.0
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Remote Branch                    : 
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Remote Branch                    : 
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Reconstruct Branch               : 
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
11-22 12:16:05.736 25325 25351 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
11-22 12:16:05.738 25325 25325 V GraalActivity: surfaceCreated for com.gluonhq.helloandroid.MainActivity@c81e601
11-22 12:16:05.738 25325 25325 V GraalActivity: loading substrate library
11-22 12:16:05.771 25325 25325 D AndroidRuntime: Shutting down VM
11-22 12:16:05.772 25325 25325 E AndroidRuntime: FATAL EXCEPTION: main
11-22 12:16:05.772 25325 25325 E AndroidRuntime: Process: de.rpgframework.splittermond.mondtor, PID: 25325
11-22 12:16:05.772 25325 25325 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZdaPv" referenced by "/data/app/~~ldg4MGwcu79H52ZEqGiwNg==/de.rpgframework.splittermond.mondtor-l4yK4VsxUEpjw60lKop40g==/lib/arm64/libsubstrate.so"...
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.SurfaceView.updateSurface(SurfaceView.java:1153)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3074)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1946)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8156)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-22 12:16:05.772 25325 25325 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-22 12:16:05.773 25325 25351 I AdrenoGLES-0: PFP: 0x016dd090, ME: 0x00000000
11-22 12:16:05.776 25325 25351 E Adreno-AppProfiles: Could not find QSPM HAL service
11-22 12:16:05.776  1635 25355 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
11-22 12:16:05.776  1635  6609 W ActivityTaskManager:   Force finishing activity de.rpgframework.splittermond.mondtor/com.gluonhq.helloandroid.MainActivity
11-22 12:16:05.781 25325 25351 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
11-22 12:16:05.781 25325 25351 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
```

### PR DESCRIPTION
**Pull request by jperedadnr**
Deploying to Android 11 fails because of missing symbols. Adding `libstdc++` fixes it. This PR also provides support for C++ in native libraries. 

### Issue

Fixes #840 and #774

### Progress

- [x] Change must not contain extraneous whitespace
- [x] License header year is updated, if required
- [x] Verify the contributor has signed [Gluon Individual Contributor License Agreement (CLA)](https://docs.google.com/forms/d/16aoFTmzs8lZTfiyrEm8YgMqMYaGQl0J8wA0VJE2LCCY)

### CODE REVIEW

File: src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java [hunk 1]
```diff
@@ -77,6 +76,7 @@
     private final String sdk;
     private final Path ldlld;
     private final Path clang;
+    private final Path clangplus;
```
Comment (johanvos) [inline src/main/java/com/gluonhq/substrate/target/AndroidTargetConfiguration.java:79]: use cpp or clangpp

**Comment by bubbleguuum** [comment]
beware that statically linking libc++_shared (with -static-libstdc++) has some implications explained in:
https://developer.android.com/ndk/guides/cpp-support#selecting_a_c_runtime

Notably:
If your application includes multiple shared libraries, you should use libc++_shared.so.

However:
If all of your application's native code is contained in a single shared library, we recommend using the static runtime. This allows the linker to inline and prune as much unused code as possible, leading to the most optimized and smallest application possible. It also avoids PackageManager and dynamic linker bugs in old versions of Android that make handling multiple shared libraries difficult and error-prone.

**Comment by johanvos** [comment]
Good point. We don't know upfront if there will be 1 or more native libs requiring c++ libs, so it's a difficult situation.
Using the shared library seems to be the safe approach then, but less efficient. Also, it might require adding this shared lib into the APK as well, as it might not be present on (all) Android runtimes, I believe?

**Comment by bubbleguuum** [comment]
Yes the shared lib must be included:
"On Android, the libc++ used by the NDK is not the same as the one that's part of the OS. This gives NDK users access to the latest libc++ features and bug fixes even when targeting old versions of Android. The trade-off is that if you use libc++_shared.so, you must include it in your APK. If you're building your application with Gradle this is handled automatically."

I suppose going the static route is simplier and will work in most cases. Maybe if there is the need later, it is possible to add a user configurable setting to specify dynamic linking (and package libc++_shared.so in the APK in the process).

**Comment by johanvos** [comment]
Agreed. I created https://github.com/gluonhq/substrate/issues/865 to track this.

**Review by johanvos — APPROVED** [review]
