### PR TITLE
LogProcess can write to console when running on CI

### LINKED ISSUE #815: Print logProcess also to console on CI
When ProcessRunner fails, `logProcess` is used to log the process input/output/error to a file. When running on CI, this file is not accessible, so it could be logged to the console as well.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #815

### CODE REVIEW

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/com/gluonhq/substrate/HelloFXTest.java  2
- src/test/java/com/gluonhq/substrate/HelloGluonTest.java  2
- src/test/java/com/gluonhq/substrate/HelloWorldTest.java  2
- src/test/java/com/gluonhq/substrate/HelloFXMLTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=6371637&bid=20675791)

File: src/main/java/com/gluonhq/substrate/util/ProcessRunner.java [hunk 1]
```diff
@@ -64,6 +64,7 @@
     private boolean interactive;
 
     private static Path processLogPath;
+    private static boolean ciEnvironment;
```
Comment (johanvos) [inline src/main/java/com/gluonhq/substrate/util/ProcessRunner.java:67]: I think this is not really specific to CI. I do understand the idea, but it might be better to rename it to "consoleProcessLogging" or so.

Comment (jperedadnr) [reply src/main/java/com/gluonhq/substrate/util/ProcessRunner.java]: Makes sense, renamed

**Comment by eugener** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/com/gluonhq/substrate/HelloWorldTest.java  2
- src/test/java/com/gluonhq/substrate/HelloGluonTest.java  2
- src/test/java/com/gluonhq/substrate/HelloFXTest.java  2
- src/test/java/com/gluonhq/substrate/HelloFXMLTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/gluonhq/substrate/pullRequest?prid=6371637&bid=20675791)

**Review by johanvos — APPROVED** [review]
